- name: Set system defaults
  script: set-defaults.sh
  changed_when: false

- name: Install homebrew packages
  homebrew: name={{item}} state=latest
  with_items: '{{homebrew_packages}}'

- name: Tap into homebrew/cask-fonts
  homebrew_tap: tap=homebrew/cask-fonts state=present

- name: Tap into homebrew/cask-versions
  homebrew_tap: tap=homebrew/cask-versions state=present

- name: Install apps with homebrew cask
  homebrew_cask: name={{item}} state=present
  with_items: '{{homebrew_cask_packages}}'

- name: Install mas
  homebrew: name=mas state=latest

- name: Install Mac-App-Store-only apps with mas
  command: mas install {{item}}
  with_items: '{{mas_packages}}'
