---
# Custom Terminal theme.
- name: Get current Terminal profile.
  shell: defaults read com.apple.terminal 'Default Window Settings'
  register: terminal_theme
  changed_when: false
  check_mode: no

- name: Ensure custom Terminal profile is added.
  shell: open "{{ dotfiles_home }}/roles/terminal/files/One-Dark.terminal"
  changed_when: false
  when: "'One-Dark' not in terminal_theme.stdout"

# TODO: This doesn't work in Yosemite. Consider a different solution?
- name: Ensure custom Terminal profile is set as default.
  shell: "{{ item }}"
  with_items:
    - defaults write com.apple.terminal 'Default Window Settings' -string One-Dark
    - defaults write com.apple.terminal 'Startup Window Settings' -string One-Dark
  changed_when: false
  when: "'One-Dark' not in terminal_theme.stdout"
